### ISSUE TITLE
Cannot access rsl_rl repository on BitBucket

### ISSUE THREAD

**Issue by mcx** [leggedrobotics/legged_gym#1]
Step 4 of the Installation requires access to the [rsl_rl repository](https://bitbucket.org/leggedrobotics/rsl_rl/).
> Install rsl_rl (PPO implementation)
> Clone https://bitbucket.org/leggedrobotics/rsl_rl/src/master/
> cd rsl_rl && git checkout develop && pip install -e .

However navigating to the URL gives an error:
> We can't let you see this page
> To access this page, you may need to log in with another account. You can also return to the previous page or go back to your dashboard.

`rsl_rl` is also not visible from the [main Robotics Systems Lab BitBucket page](https://bitbucket.org/leggedrobotics/). Is the repository not publically available?

**Comment by nikitardn** [comment]
The link should point to the open GitHub version. It is fixed now. Thank you for reporting!
