### ISSUE TITLE
Unable to specify GPU device on multi-GPU setup

### ISSUE THREAD

**Issue by derektan95** [leggedrobotics/legged_gym#10]
**Describe the bug**
Unable to specify the GPU device to use on multi-GPU setup

**To Reproduce**
1. Execute `python train.py --graphics_device_id=0 --task=a1`
2. On seperate terminal, execute `python train.py --graphics_device_id=1 --task=a1`
3. Observe that for both terminals, selected GPU device is still `cuda:0`.

**Expected behavior**
Selected GPU device should show `cuda:0` and `cuda:1` on the different terminals. 

**System (please complete the following information):**
 - Commit: 9ddda29
 - OS: Ubuntu 18.04
 - GPU: 4x A5000
 - CUDA: 11.4
 - GPU Driver: 470.82.01

**Comment by derektan95** [comment]
Hi @tomlankhorst, 

This works well too. Thanks alot!

**Comment by bwrooney82** [comment]
@dmtrung14 Hi, I have the same questions too. Do you have any solutions now?

**Comment by 242726Yuncheng** [comment]
> [@dmtrung14](https://github.com/dmtrung14) Hi, I have the same questions too. Do you have any solutions now?

Me too, I noticed that in helper.py there is a parameter called “horovod” which is supposed to enable distributed training. However, after I set it to true, nothing seems to change. Do you happen to know anything else about this?
