### ISSUE TITLE
Sim-to-real Implementation

### ISSUE THREAD

**Issue by anahrendra** [leggedrobotics/legged_gym#14]
Hello, 

 I am wondering if you have any guideline for the sim-to-real deployment.
 I am planning to deploy the learned policy in the Unitree A1 Robot

Thanks in advance!

**Comment by nikitardn** [comment]
Hi, sim-to-real deployment is very platform/task specific. You can read our paper to have an idea of what we are doing to ensure a successful transfer.

**Comment by DaveDe** [comment]
Hi,

I'm also trying to deploy learned policies on the Unitree A1 robot. I have successfully done a sim-to-sim transfer (Isaac Gym to PyBullet). For whatever reason, deploying on my real robot is not yet working (the robot's joints reach extreme angles after a few actions). The policy query takes under 4ms, so I imagine latency isn't a huge issue?

I'm curious if anyone else has successfully transferred to a real robot, and is willing to share any overall guidelines, or implementation details. I'd be glad to share my sim-to-sim transfer code if anyone finds it useful.

Thanks

**Comment by JeffXu1** [comment]
> Hi,
> 
> I'm also trying to deploy learned policies on the Unitree A1 robot. I have successfully done a sim-to-sim transfer (Isaac Gym to PyBullet). For whatever reason, deploying on my real robot is not yet working (the robot's joints reach extreme angles after a few actions). The policy query takes under 4ms, so I imagine latency isn't a huge issue?
> 
> I'm curious if anyone else has successfully transferred to a real robot, and is willing to share any overall guidelines, or implementation details. I'd be glad to share my sim-to-sim transfer code if anyone finds it useful.
> 
> Thanks
Hi，could you share your sim to sim tansrferr code, I 'm also trying to deploy it on the Unitree A1 robot.

**Comment by hzlbbfrog** [comment]
Hi,
I am also trying to do the sim-to-real implementation. 
I also wonder if someone has made a successful transfer and may post an overall guideline. 
aiming at the specific plateform or hardware is also helpful!
Thank you!
