### ISSUE TITLE
There Is No develop Branch & Some Suggestions

### ISSUE THREAD

**Issue by Zhehui-Huang** [leggedrobotics/legged_gym#2]
- In the README file:
`cd rsl_rl && git checkout develop && pip install -e .`
but there is no develop branch in the rsl_rl.
`cd legged_gym && git checkout develop && pip install -e .`
same, there is no develop branch in this (legged_gym) repository
- Besides, I think the pull request from [sheim](https://github.com/leggedrobotics/rsl_rl/pull/2/commits/c712131a60ee16ee037f46876d781b5335c90c5d) is reasonable, there are duplicate codes, `packages=find_packages()`, which can make `pip install -e .`  fail. It would be great if the author/maintainer could merge the pull request.
- `Try running an example python examples/1080_balls_of_solitude.py` should be changed to `cd examples`, and try running an example `python 1080_balls_of_solitude.py`

**Comment by nikitardn** [comment]
Thank you for reporting. It is fixed now
