### ISSUE TITLE
Different URDF with Official Unitree A1

### ISSUE THREAD

**Issue by Baichenjia** [leggedrobotics/legged_gym#27]
**Describe the bug**
The URDF of A1 is different fromthe official URDF file at
https://github.com/unitreerobotics/unitree_ros/blob/master/robots/a1_description/urdf/a1.urdf

If I train a policy with your asset, can I transfer the policy to a real A1 robot?

I try to replace the urdf file with the official one, and I got a score **zero** after 5000 epochs training. How can I train a reasonable policy with the official asset?

**Comment by Vassil17** [comment]
In case anyone comes across this, it seems that adding the flag " dont_collapse="true" " to the *_foot_fixed joints fixes this issue.
