### ISSUE TITLE
[Question] Troubles with play.py script after training

### ISSUE THREAD

**Issue by LouisEnslin99** [leggedrobotics/legged_gym#39]
Hi,

I am encountering issues with the `play.py` script after training my robot. During training, the robot moves as expected, but when I attempt to use the trained network with `play.py`, the robot barely moves and remains stationary. This issue is not limited to any specific robot models, as I also have experienced this problem with both `anymal` and `a1`.

Currently, I am running everything on the CPU. Could this be the reason for the problem? Are there any specific parameters that I need to adjust for `play.py` to work correctly with my trained network?

Any recommendations or advice would be greatly appreciated. Thank you in advance.

Best regards,

Louis

![Plots](https://user-images.githubusercontent.com/57998941/227228313-e04bc47d-dd0c-4e67-9aea-5e6a71f7be86.png)

**Comment by nooshin-kohli** [comment]
Hi, 

I am facing the same issue. Do you have any updates on this? 

Any advice would be appreciated. Thank you.

Best regards,

Nooshin

**Comment by ssunkyu** [comment]
Hi,

I've had a similar problem.

I solved the problem by changing **"train_cfg.runner.resume"** in play.py to True.

I hope it helped you.

Best regards,

Song
