### ISSUE TITLE
The new issac-lab repo

### ISSUE THREAD

**Issue by guyo-shifters** [leggedrobotics/legged_gym#69]
Thank you for an amazing work!
regarding your last comment on migration to orbit and isaac-lab, the link you included is no longer working.
can you link to the new repo? or add instructions on how to use isaac-lab to run this code?

**Comment by Mayankm96** [comment]
Thanks for bringing this to our notice. The links are fixed now :)

**Comment by formoree** [comment]
the link you included is no longer working again.
